from selenium import webdriver
from selenium.webdriver.common.by import By
import time
print ("Ведите имя пользователя:")
username = input()
print ("Ведите пароль")
password = input()
print ("Ведите периуд поиска:")
period = input()
def login(a,b,c):
    try:
        options = webdriver.ChromeOptions()
        options.add_experimental_option('excludeSwitches', ['enable-logging'])
        print ("Открываем броузер")
        browser = webdriver.Chrome('chromedriver.exe',options=options)
        browser.get('https://telemetr.me/')
        time.sleep(3)
        print ("Нажимаем конпку входа") 
        button_auth = browser.find_element(By.XPATH, '//*[@id="btn_auth"]')
        button_auth.click()
        print (f"Вводим логин {a}")
        USERNAME =  browser.find_element(By.XPATH, '/html/body/div[2]/div/div/div[2]/form/div[1]/input')        #browser.find_element_by_name('login[email]')
        USERNAME.clear()
        USERNAME.send_keys(a)
        time.sleep(3)
        print (f"Вводим пароль {b}")
        PASSWORD =  browser.find_element(By.XPATH, '/html/body/div[2]/div/div/div[2]/form/div[2]/input')        #browser.find_element_by_name('login[email]')
        PASSWORD.clear()
        PASSWORD.send_keys(b)
        time.sleep(3)
        print ("Входим в систему")
        button_auth = browser.find_element(By.XPATH, '/html/body/div[2]/div/div/div[2]/form/button')
        button_auth.click()
        time.sleep(5)
        print ("Заходим в посты")
        browser.get('https://telemetr.me/posts')
        time.sleep(3)
        print (f"Вводим дату которая вам нужна[{c}]")
        DATE = browser.find_element(By.XPATH, '//*[@id="period"]')
        DATE.clear()
        DATE.send_keys(c)
        time.sleep(1)
        print ("Нажимаем ok ")
        button_ok = browser.find_element(By.XPATH, '/html/body/div[4]/div[4]/button[2]')
        button_ok.click()
        time.sleep(3)
        print ("Ишем данные") 
        button_serch = browser.find_element(By.XPATH, '/html/body/div[3]/div/div[2]/div[2]/div/form/div/div[2]/button')
        button_serch.click()
        time.sleep(5)
        print ("Сохрянем данные в файл")
        time.sleep(3)
        print ("Послыаем данные в телеграм  пользователя")
        time.sleep(3)
        print ("Скрипт завершает работу..")
        browser.close()
        browser.quit()
    except Exception as ex:
        print (f"ERROR = {ex}")
        browser.close()
        browser.quit()
     

login(username,password,period)
 
